config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :educations
  resources :experiences
  resources :publications
  resources :awards

end

app/models/award.rb
class Award < ActiveRecord::Base
end

app/models/education.rb
class Education < ActiveRecord::Base
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
	before_action :find_edu, only: [:show, :edit, :update, :destroy]

	def index
	end

	def new
		@education=Education.new
	end

	def create
		@education=Education.new edu_params

		if @education.save
			redirect_to @education
		else
			render 'new'
		end
	end

	def show
	end

	def edit
		
	end

	def update
		if @education.update edu_params
			redirect_to @education
		else
			render 'edit'
		end
	end

	def destroy
		@education.destroy
		redirect_to educations_path
	end

	private

	def edu_params
		params.require(:education).permit(
			:institution,
			:degree,
			:start,
			:end,
			:short_description,
			:full_description
		)
	end

	def find_edu
		@education = Education.find(params[:id])
	end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@education = Education.all.order("start ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/educations/_form.html.erb
<%= form_for @education do |f| %>
  <p>
    <%= f.label :institution %><br>
    <%= f.text_field :institution %>
  </p>

  <p>
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </p>

  <p>
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </p>

  <p>
    <%= f.label :end %><br>
    <%= f.text_field :end %>
  </p>

  <p>
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </p>
 
  <p>
    <%= f.label :full_description %><br>
    <%= f.text_area :full_description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/educations/edit.html.erb
<h1>Edit Education</h1>
<%= render 'form'%>

app/views/educations/new.html.erb
<h1>Add new Education section!</h1>
<%= render 'form'%>

app/views/educations/show.html.erb
<%= @education.institution %> <br>
<%= @education.degree %> <br>
<%= @education.start %> - <%= @education.end %> <br>
<%= @education.full_description %>

<br>
<br>

<%= link_to "Edit", edit_education_path(@education) %>
<%= link_to "Delete", education_path(@education), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Marcial Puchi - Portfolio</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

	</body>
</html>

app/views/welcome/index.html.erb
<section id="landing">

	<header class="wrapper_wide cf">
		<a href="#" id="logo">MARCIAL PUCHI</a>
		<ul id="nav">
			<li><a href="#">About Me</a></li>
			<li><a href="#">Experience</a></li>
			<li><a href="#">Education</a></li>
			<li><a href="#">Awards</a></li>
			<li><a href="#">Contact</a></li>
		</ul>
	</header>

	<div class="hero-content wrapper">
		<h1>Marcial Puchi</h1>
		<h4>Postgraduate Student at The University of Edinburgh</h4>
		<a href="http://uk.linkedin.com/in/marcialpuchi" target="_blank"><i class="fa fa-linkedin"></i></a>
		<a href="http://github.com/marcialpuchi" target="_blank"><i class="fa fa-github"></i></a>
		<%= link_to "cv.pdf", :target => '_blank' do%>
		  <i class="fa fa-file"></i>
		<% end %>
	</div>
</section>

<section id="about">
	<div class="wrapper_skinny">
		<div class="profile-pic"></div>
		<h1>About me</h1>
		<p>Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. Nearly-Headless Nick now string them together, and answer me this, which creature would you be unwilling to kiss? Poltergeist sticking charm, troll umbrella stand flying cars golden locket Lily Potter. Pumpkin juice Trevor wave your wand out glass orbs, a Grim knitted hats. Stan Shunpike doe patronus, suck his soul Muggle-Born large order of drills the trace. Bred in captivity fell through the veil, quaffle blue flame ickle diddykins Aragog. Yer a wizard, Harry Doxycide the woes of Mrs. Weasley Goblet of Fire.</p>

		<p>Toad-like smile Flourish and Blotts he knew I’d come back Quidditch World Cup. Fat Lady baubles banana fritters fairy lights Petrificus Totalus. So thirsty, deluminator firs’ years follow me 12 inches of parchment. Head Boy start-of-term banquet Cleansweep Seven roaring lion hat. Unicorn blood crossbow mars is bright tonight, feast Norwegian Ridgeback. Come seek us where our voices sound, we cannot sing above the ground, Ginny Weasley bright red. Fanged frisbees, phoenix tears good clean match.</p>

	</div>
</section>

<section id="exp">
	<div class="">
		<h1>Experience</h1>
		<div id="cd-timeline" class="cd-container">
			<div class="cd-timeline-block">
				<div class="cd-timeline-img">
					<img src="assets/HP.svg" alt="Hewlett-Packard" class="hp">
				</div> <!-- cd-timeline-img -->

				<div class="cd-timeline-content">
					<h2>Advanced Prototyper / Research Assistant</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde?</p>
					<a href="#0" class="cd-read-more">Read more</a>
					<span class="cd-date">Jan 18</span>
				</div> <!-- cd-timeline-content -->
			</div> <!-- cd-timeline-block -->

			<div class="cd-timeline-block">
				<div class="cd-timeline-img cd-picture">
					<img src="assets/ucol.png" alt="University of Colima" class="ucol">
				</div> <!-- cd-timeline-img -->

				<div class="cd-timeline-content">
					<h2>Software Developer (Internship)</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, obcaecati, quisquam id molestias eaque asperiores voluptatibus cupiditate error assumenda delectus odit similique earum voluptatem doloremque dolorem ipsam quae rerum quis.</p>
					<a href="#0" class="cd-read-more">Read more</a>
					<span class="cd-date">Jan 24</span>
				</div> <!-- cd-timeline-content -->
			</div> <!-- cd-timeline-block -->

			<div class="cd-timeline-block">
				<div class="cd-timeline-img cd-location">
					<img src="assets/otago.svg" alt="University of Otago" class="otago">
				</div> <!-- cd-timeline-img -->

				<div class="cd-timeline-content">
					<h2>Web Developer (Course Project)</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.</p>
					<a href="#0" class="cd-read-more">Read more</a>
					<span class="cd-date">Feb 14</span>
				</div> <!-- cd-timeline-content -->
			</div> <!-- cd-timeline-block -->

			<div class="cd-timeline-block">
				<div class="cd-timeline-img cd-location">
					<img src="assets/ucol.png" alt="University of Colima" class="ucol">
				</div> <!-- cd-timeline-img -->

				<div class="cd-timeline-content">
					<h2>Software Developer (Internship)</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
					<a href="#0" class="cd-read-more">Read more</a>
					<span class="cd-date">Feb 18</span>
				</div> <!-- cd-timeline-content -->
			</div> <!-- cd-timeline-block -->
		</div> <!-- cd-timeline -->
	</div>
</section>

<section id="edu">
	<h1>Education</h1>
	<ul class="education timeline" id="timeline">
		<% @education.each do |edu|%>
			<li class="li complete">
				<div class="timestamp">
			     	<span class="author"><%= edu.institution %></span>
			     	<span class="date"><%= edu.start.strftime("%B %Y") %> - <%= edu.end.strftime("%B %Y") %><span>
			    </div>
			    <div class="status">
			     	<h4><%= edu.degree %></h4>
			     	<span class="logo"></span>
			    </div>
			</li>
		<% end %>
	</ul>
</section>

<section id="awards">
	<div class="wrapper_skinny">
		<h1>Awards</h1>
	</div>
</section>
<section id="contact">
	<div class="wrapper_skinny">
		<h1>Contact</h1>
	</div></section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/trianglify/0.4.0/trianglify.min.js"></script>